enablePlugins(PlayScala)

enablePlugins(PlayScalaJS)

name := "total-stargazers"

lazy val root = project in file(".") dependsOn sdk

lazy val js = project

lazy val sdk = project

scalaJSProjects := Seq(js)

scalaVersion in ThisBuild := "2.11.7"

routesGenerator := InjectedRoutesGenerator

val haxeJsFiles = taskKey[Seq[File]]("JavaScript files generated by Total Stargazer SDK")

haxeJsFiles := {
  val Seq(jsFile) = (haxe in sdk in Js).value
  val destinationFile = (sourceManaged in Assets).value / "total-stargazer-sdk.js"
  IO.copyFile(jsFile, destinationFile)
  Seq(destinationFile)
}

resourceGenerators in Assets <+= haxeJsFiles

libraryDependencies += "com.thoughtworks.each" %% "each" % "0.5.1"

libraryDependencies += "com.thoughtworks.microbuilder" %% "microbuilder-play" % "1.0.3"

libraryDependencies += "org.webjars.bower" % "browser-request" % "0.2.1"
